### ISSUE TITLE
Services and Device tracker dissapeared after last update

### ISSUE THREAD

**Issue by misko903** [turbulator/pandora-cas#22]
Hello,
after last update I can't see any of the `Services` and `Device Trackers`. I have deleted and redownloaded addon, but the problem still persist. 23 `Sensors` are present.

**Comment by turbulator** [comment]
Fixed in 1.4.8

**Comment by misko903** [comment]
Still the same here:

![Image](https://github.com/user-attachments/assets/c080902e-2f56-4d4d-a7ee-f810c8dfc31f)
